# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f599e440b1f91e8b3cf6fbb90be5d7e49ec8162b082e3ca9a760617d68d91fb354fe069ebc1c38b9b1961900cb19681ff125c5de8cf9875c2282bbee2f06fc3

test:
  secret_key_base: 85a8782122724ea4ad5fd25a41205720612917a240fdec3ce0486a56bd1ab0a586fc2e0215cdff4e55469290745e631b3e85ea2651bbb3af7d3dd1eeece7d157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
